# =============================================================================
# Binance API Configuration
# =============================================================================
binance:
  # Trading pair symbol
  symbol: "BTCUSDT"
  # Kline interval: 1d for daily data
  interval: "1d"
  # Number of years of historical data to fetch
  years_of_data: 2

# =============================================================================
# Prophet Model Configuration
# =============================================================================
prophet:
  # Column to use as target variable for forecasting
  price_column: "close"
  
  # Seasonality mode: 'additive' or 'multiplicative'
  # For crypto, multiplicative often works better due to price volatility
  seasonality_mode: "multiplicative"
  
  # Seasonality components
  yearly_seasonality: true
  weekly_seasonality: true
  daily_seasonality: false  # Not needed for daily data
  
  # Changepoint prior scale: higher = more flexible trend
  # For volatile assets like BTC, a value between 0.1-0.5 works well
  changepoint_prior_scale: 0.5
  
  # Seasonality prior scale: higher = more flexible seasonality
  seasonality_prior_scale: 10.0
  
  # Proportion of data used for changepoint detection
  changepoint_range: 0.9  # Use 90% of data for changepoint detection

  # Whether to add volume as an additional regressor
  add_volume_regressor: false
  
  # Test set size in days for model evaluation
  test_size_days: 30

# =============================================================================
# Forecast Configuration
# =============================================================================
forecast:
  # Number of days to forecast into the future
  days_ahead: 30

# =============================================================================
# MLOps Configuration
# =============================================================================
mlops:
  # Model metadata for tracking and governance
  model:
    name: "crypto_ts_forecast_prophet"
    description: "Prophet time series model for Bitcoin price forecasting"
    owner: "data_science_team"
    
  # Model versioning and lifecycle
  versioning:
    # Automatically register model in MLflow Model Registry
    register_model: true
    
    # Model stage (None, Staging, Production, Archived)
    # Set to "Staging" for newly trained models
    default_stage: "Staging"
    
    # Version tagging strategy
    tags:
      task: "time_series_forecasting"
      asset_class: "cryptocurrency"
      symbol: "BTCUSDT"
      framework: "prophet"
      
  # Model performance thresholds for production deployment
  # Models must meet these criteria to be promoted to Production
  deployment_thresholds:
    min_r2: 0.7  # Minimum R² score
    max_mape: 15.0  # Maximum MAPE percentage
    min_test_samples: 20  # Minimum test samples required
    
  # Monitoring and alerting
  monitoring:
    # Enable data drift detection
    enable_drift_detection: false
    
    # Alert thresholds for production models
    alert_thresholds:
      mape_degradation_pct: 20  # Alert if MAPE increases by this %
      prediction_latency_ms: 1000  # Alert if prediction takes longer
